title: 'Slide templates'

baseurl: '/slide-templates'

highlighter: rouge

collections:
  type:
    output: true
  slides:
    output: true

slide:
  paths:
    base: 'assets/slides'

  # Dopo l'aggiunta di pagine "type", aggiungi i tag qui.
  # Il campo `key` viene usato nell'URL.
  tags:
    - key: 'general'
      value: 'Generale'
    - key: 'organigram'
      value: 'Organigramma'

  data:
    - 
      # Ricordarsi di suddividere i template per tipo usando i nomi
      # delle directory.

      # Percorso file Powerpoint.
      path: 'assets/slides/general/pptx/0.pptx'

      # Percorso file immagine anteprima.
      preview: 'assets/slides/general/preview/0.jpg'

      # Testo alternativo all'immagine anteprima quando non presente.
      alt: 'Slide 0'

      # In futuro si potranno aggiungere altri campi in base alle necessità.

    - path: 'assets/slides/general/pptx/1.pptx'
      preview: 'assets/slides/general/preview/1.jpg'
      alt: 'Slide 1'

    - path: 'assets/slides/organigram/pptx/2.pptx'
      preview: 'assets/slides/organigram/preview/2.jpg'
      alt: 'Slide 2'

    - path: 'assets/slides/organigram/pptx/3.pptx'
      preview: 'assets/slides/organigram/preview/3.jpg'
      alt: 'Slide 3'

    - path: 'assets/slides/organigram/pptx/OrganigrammaPROVA.pptx'
      preview: 'assets/slides/organigram/preview/PROVA1.png'
      alt: 'Organigramma PROVA'

# File da non servire nel sito.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
